// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_newbie = "CgkIq96do8IdEAIQAg"; // <GPGSID>
        public const string achievement_amateur_collector = "CgkIq96do8IdEAIQBQ"; // <GPGSID>
        public const string achievement_trail_explorer = "CgkIq96do8IdEAIQCQ"; // <GPGSID>
        public const string achievement_passionate_collector = "CgkIq96do8IdEAIQBg"; // <GPGSID>
        public const string achievement_not_a_n00b = "CgkIq96do8IdEAIQCw"; // <GPGSID>
        public const string achievement_novice = "CgkIq96do8IdEAIQAw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIq96do8IdEAIQDA"; // <GPGSID>
        public const string achievement_suckling = "CgkIq96do8IdEAIQAQ"; // <GPGSID>
        public const string achievement_trail_master = "CgkIq96do8IdEAIQCg"; // <GPGSID>
        public const string achievement_collector = "CgkIq96do8IdEAIQBA"; // <GPGSID>
        public const string achievement_spy = "CgkIq96do8IdEAIQCA"; // <GPGSID>
        public const string achievement_first_blood = "CgkIq96do8IdEAIQBw"; // <GPGSID>

}

